### ISSUE TITLE
Data Ingestion

### ISSUE THREAD

**Issue by Prinstan** [variationalkk/User-and-Entity-Behavior-Analytics-UEBA#1]
Fantastic effort in making the logic.
I would suggest following details to complete the project

1. Source: INPUT required from real world tools like SIEM / ELK Stack
2. Processing: Which you already have done may have to modify according to the source.
3. Alert: If any suspect detect, Alerts should trigger ref. for open source tool like elastalert.
4. Report: Need to generate report using ELK Kibina. 

Or let me know how are you expecting to get the data in real world scenario and not sample data CERT/R4.2.

I would like to participate in your project

**Comment by variationalkk** [comment]
Hi, sorry for the late reply.
Thanks for your suggestions. I have stopped this research because of some reasons recently. Maybe I will update this project, or maybe not. So, you can continue this reasearch in your own project. 
Good Luck!
